predictors = [
    'Battles (t-1)',
    'Explosions/Remote violence (t-1)',
    'Protests (t-1)',
    'Riots (t-1)',
    'Strategic developments (t-1)',
    'Violence against civilians (t-1)',
    'Excessive force against protesters (t-1)',
    'Agreement (t-1)',
    'Explosions/Remote violence_neighbours (t-1)',
    'Strategic developments_neighbours (t-1)',
    'Protests_neighbours (t-1)',
    'Violence against civilians_neighbours (t-1)',
    'Battles_neighbours (t-1)',
    'Riots_neighbours (t-1)',
    'linear_month_trend',
    'year',
    'month_2',
    'month_3',
    'month_4',
    'month_5',
    'month_6',
    'month_7',
    'month_8',
    'month_9',
    'month_10',
    'month_11',
    'month_12',
    'quarter_2',
    'quarter_3',
    'quarter_4',
    'importance_weight',
    "inflation",
    "youth_unemployment",
    "income_inequality",
    "income_level_code",
    'christian_holiday_count',
    'islam_holiday_count',
    'shia_holiday_count',
    'hindu_holiday_count',
    'buddhist_holiday_count',
    'jewish_holiday_count',
    'cultural_holiday_count',
    'nonreligious_holiday_count',
    'majority_religion',
    'majority_pct',
    'minority1_religion',
    'minority1_pct',
    'minority2_religion',
    'minority2_pct',
    'nonreligpct',
    ]

targets = [
    'Battles',
    'Explosions/Remote violence',
    'Violence against civilians'
    ]